name: Enchancement
description: Propose enchancement
title: "[Enchancement] "
labels: [ "enchancement" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of what the enchancement is.
      placeholder: eg. It would be cool if player would ...
    validations:
      required: true
  - type: markdown
    id: tip
    attributes:
      value: |
        Any additional context shall be provided in comments to this bug report.
        Reference feature issue, eg. #10, or you can add code snippet or screenshots.
